admins: fnux;sapin;lambda
secret: ffffffffffffffffffffffffffffffffffffffffffffffff
reloader: true
database:
   adapter: sqlite3
   database: tmp/app.db
   # if adapter setted to MySQL
   user: blurps
   password: blurps
   server: blurps
